<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ExternalServices\" />
    <Folder Include="DependencyInjection\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkillToHire.Application\SkillToHire.Application.csproj" />
    <ProjectReference Include="..\SkillToHire.Domain\SkillToHire.Domain.csproj" />
  </ItemGroup>

</Project>
